version: '3'
services: 
  serviceregistry:
    image: 'sankar/serviceregistry:0.0.1'
    container_name: serviceregistry
    ports:
      - '8761:8761'
  configserver:
    image: 'sankar/configserver:0.0.1'
    container_name: configserver
    ports:
      - '9095:9095'
    environment:
      - EUREKA_SERVER_ADDRESS=http://serviceregistry:8761/eureka
    healthcheck:
      test: ["CMD", "curl", "-f", "http://configserver:9095/actuator/health"]
      interval: 10s
      retries: 5
    depends_on:
      - serviceregistry
  cloudgateway:
    image: 'sankar/cloudgateway:latest'
    container_name: cloudgateway
    ports: 
      - '9092:9092'
    environment:
      - EUREKA_SERVER_ADDRESS=http://serviceregistry:8761/eureka
      - CONFIG_SERVER_URL=configserver
    depends_on:
        configserver:
          condition: service_healthy
