server:
  port : 9092


spring:
  application:
    name: API-GATEWAY
  config:
    import: configserver:http://${CONFIG_SERVER_URL:localhost}:9095
  cloud:
    gateway:
      routes:
        - id: ORDER-SERVICE
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/order/**
          filters:
            - name: CircuitBreaker
              args:
                name: ORDER-SERVICE
                fallbackuri: forward:/orderServiceFallBack
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 1
                redis-rate-limiter.burstCapacity: 1
#                redis-rate-limiter.requestedTokens: 1
#                key-resolver: "userKeySolver"
        - id: PAYMENT-SERVICE
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/payment/**
          filters:
            - name: CircuitBreaker
              args:
                name: PAYMENT-SERVICE
                fallbackuri: forward:/paymentServiceFallBack
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 1
                redis-rate-limiter.burstCapacity: 1
#                redis-rate-limiter.requestedTokens: 1
#                key-resolver: "userKeySolver"
        - id: PRODUCT-SERVICE
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/product/**
          filters:
            - name: CircuitBreaker
              args:
                name: PRODUCT-SERVICE
                fallbackuri: forward:/productServiceFallBack
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 1
                redis-rate-limiter.burstCapacity: 1
#                redis-rate-limiter.requestedTokens: 1
#                key-resolver: "userKeySolver"


okta:
  oauth2:
    issuer: https://dev-46337844.okta.com/oauth2/default
    audience: api://default
    client-id: 0oa7fgj2ndDkWSiYn5d7
    client-secret: QZ1jNe9nErndHjpFeb084V9Jp-HHbReNT_QS4nXW
    scopes: openid, profile, email, offline_access

